### ISSUE TITLE
[bug]: ktor 3.x incompatibility

### ISSUE THREAD

**Issue by pwspot** [algolia/algoliasearch-client-kotlin#429]
### Description

Search client fails with ktor 3.0.0 due to missing io/ktor/client/plugins/contentnegotiation/ContentNegotiation class that seems to have moved to [ContentNegotiationConfig](https://api.ktor.io/ktor-server/ktor-server-plugins/ktor-server-content-negotiation/io.ktor.server.plugins.contentnegotiation/-content-negotiation-config/index.html).

Changes introduced in https://github.com/ktorio/ktor/pull/3760/files#diff-1bf65602859dcd4cad17f5752ec526be5d9c6fdc8b5725b644876cab3fe2e088

### Client

Search

### Version

2.1.12

### Relevant log output

```shell
java.lang.NoClassDefFoundError: io/ktor/client/plugins/contentnegotiation/ContentNegotiation
    at com.algolia.search.configuration.internal.extension.HttpClientKt.configure(HttpClient.kt:26)
    at com.algolia.search.configuration.internal.extension.HttpClientKt$getHttpClient$2.invoke(HttpClient.kt:19)
    at com.algolia.search.configuration.internal.extension.HttpClientKt$getHttpClient$2.invoke(HttpClient.kt:19)
    at io.ktor.client.HttpClientKt.HttpClient(HttpClient.kt:643)
    at io.ktor.client.HttpClientJvmKt.HttpClient(HttpClientJvm.kt:24)
    at com.algolia.search.configuration.internal.extension.HttpClientKt.getHttpClient(HttpClient.kt:19)
    at com.algolia.search.configuration.internal.ConfigurationSearchImpl.<init>(ConfigurationSearchImpl.kt:34)
    at com.algolia.search.configuration.ConfigurationSearchKt.ConfigurationSearch(ConfigurationSearch.kt:52)
    at com.algolia.search.configuration.ConfigurationSearchKt.ConfigurationSearch$default(ConfigurationSearch.kt:38)
    at com.algolia.search.client.ClientSearchKt.ClientSearch(ClientSearch.kt:180)
    at com.algolia.search.client.ClientSearchKt.ClientSearch$default(ClientSearch.kt:174)
```
